name: 'configure aws credentials'
description: 'action to configure aws credentials from github env'

inputs:
  secret_id: 
    required: true
  secret_key:
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.secret_id }}
        aws-secret-access-key: ${{ inputs.secret_key }}
        aws-region: eu-west-1