name: Streams Lambda

on:
  push:
    branches: [ "main" ]
    paths:
      - streams-app/streams-app/**
  pull_request:
    branches: [ "main" ]
    paths:
      - streams-app/streams-app/**

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup AWS SAM CLI          
      uses: aws-actions/setup-sam@v2
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
        cache: pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest moto[mock_dynamodb2] boto3 python-env
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    #- name: Test with pytest
    #  run: |
    #    pytest Tests/lambda-test/app-test.py
    - name: Validate SAM template
      run: cd streams-app/ && sam validate
    - name: Build sam-app
      run: cd streams-app/ && sam build
    - name: Deploy to Lambda
      uses: appleboy/lambda-action@v0.1.9
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: eu-west-1
        function_name: process-streams-lambda
        source: streams-app/.aws-sam/build/StreamsLambda/*