name: Terraform Destruction

on:
  workflow_dispatch:
    branches:
      - main

permissions:
  contents: read
  issues: write
  id-token: write

jobs:
  cloud-resume-destroy:
    runs-on: ubuntu-latest
    env: 
      AWS_DEFAULT_REGION: eu-west-1
      TF_VAR_TOKEN: ${{ secrets.TOKEN }}
      TF_VAR_DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
      TF_VAR_ACM_ARN: ${{ secrets.ACM_ARN }}
      TF_VAR_BACKEND: ${{ secrets.BACKEND }}
      TF_VAR_EMAIL: ${{ secrets.MAIL }}
      TF_WARN_OUTPUT_ERRORS: 1
    steps:
      - name: checkout git repo
        uses: actions/checkout@v3
      - name: Setup AWS SAM CLI          
        uses: aws-actions/setup-sam@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
          cache: pip
      - name: build aws lambda # TESTING
        run: |
          cd sam-app/ && sam build
      - name: build aws streams-lambda # TESTING
        run: |
          cd streams-app/ && sam build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
        
      - name: AWS Commands
        run: |
          cd terraform/
          terraform init
      - name: AWS Commands
        run: |
          cd terraform/ && terraform destroy --auto-approve