name: Terraform Destruction

on:
  workflow_dispatch:
    branches:
      - main

permissions:
  contents: read
  issues: write
  id-token: write

jobs:
  cloud-resume-deploy:
    runs-on: ubuntu-latest
    env: 
      AWS_DEFAULT_REGION: eu-west-1
      TF_VAR_TOKEN: ${{ secrets.TOKEN }}
      TF_VAR_DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
      TF_VAR_ACM_ARN: ${{ secrets.ACM_ARN }}
      TF_VAR_BACKEND: ${{ secrets.BACKEND }}
    steps:
      - name: checkout git repo
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: AWS Commands
        run: |
          cd terraform/ && terraform destroy --auto-approve