name: Website

on:
  push:
    branches: [ "main" ]
    paths:
      - webpage/**
  pull_request:
    branches: [ "main" ]
    paths:
      - webpage/**

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS Credentials
      uses: szak342/cloud_resume_challenge_aws/.github/actions/configure_aws_credentials@main
      with:
        secret_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
        cache: pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest python-env requests_html
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: install chromium
      run: |
        pyppeteer-install
    - name: Test with pytest
      run: |
        pytest Tests/webpage/webpage_test.py
    - name: Sync files with s3 bucket
      run: aws s3 sync webpage/ "s3://${{ vars.S3BUCKET }}" --delete
    - name: Invalidate Cloud Front cache
      run: aws cloudfront create-invalidation --distribution-id ${{ vars.CLOUDFRONT_ID }} --paths "/*"
    - name: Webpage lambda test
      run: |
        pytest Tests/webpage/webpage-lambda-test.py